[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.11", features = ["time"] }

uuid = { version = "1.17.0", default-features = false, features = ["v4"] }
time = "0.3.41"
